"use client";
import axios from "axios";
import React from "react";
import { useQuery } from "react-query";
import Image from "next/image";
import { useRouter } from "next/router";
import { redirect } from "next/navigation";

interface ListingProp {
  params: {
    id: string;
  };
}
const ListingDetail = ({ params }: ListingProp) => {
  const slug = params.id;

  const fetchListingDetail = async () => {
    const response = await axios.get(
      `http://localhost:1337/api/arts/${slug}?populate=*`
    );
    return response.data;
  };

  const { data, isLoading, isError, error } = useQuery(
    ["listingDetail", slug],
    fetchListingDetail,
    {
      enabled: !!slug,
    }
  );

  if (isLoading) return <p>Loading...</p>;
  if (isError) return <p>Error: {error?.message}</p>;

  const imageURL = `http://localhost:1337/uploads/medium_Default_American_traditional_tattoo_of_a_beautiful_Latin_woman_0_90efccbd_533a_48b7_8bd0_94715000a03f_1_9dccfd31be.jpg`;

  return (
    <section className="py-12">
      <div className="container mx-auto px-4">
        <div className="grid gap-12 lg:grid-cols-12">
          {/* Left Column */}
          <div className="p-6 shadow-md lg:col-span-8">
            {/* Image with Rating and Favorite */}
            <div className="relative mb-6">
              <img
                src={imageURL}
                alt={data?.data?.attributes?.title}
                className="h-96 w-full rounded-lg object-cover"
              />

              <Image
                src={getArtImageLoader(
                  art?.attributes?.imageUrl?.data?.attributes?.url || ""
                )}
                alt={art.attributes.title}
                width={400}
                height={400}
                className="w-full object-cover"
              />

              {/* Add Rating and Favorite icons here */}
            </div>

            {/* Title */}
            <h1 className="mb-4 from-purple-400 to-pink-600 text-3xl font-bold">
              {data?.data?.attributes?.title}
            </h1>

            {/* Description */}
            <p className="mb-4 text-gray-600">
              {data?.data?.attributes?.description}
            </p>

            {/* Icon Details */}
            <div className="mb-4 flex space-x-4">
              {/* ... (rest of the icon details) ... */}
            </div>
          </div>

          {/* Right Column */}
          <div className="lg:col-span-4">
            {/* Buy Button */}
            <div className="mb-4">
              <button
                type="button"
                className="w-full rounded-lg bg-gradient-to-r from-purple-400 to-pink-600 px-4 py-2 text-white transition duration-300 hover:from-purple-500 hover:to-pink-700"
              >
                Buy Now for ${data?.data?.attributes?.price}
              </button>
            </div>

            {/* Buying Rules */}
            <div className="mb-4 rounded-lg p-4 shadow-md">
              <h2 className="mb-2 text-lg font-semibold">Buying Rules:</h2>
              <ul className="list-disc space-y-2 pl-5">
                <li className="text-gray-600">
                  You're allowed to sell only images generated by you!
                </li>
                <li className="text-gray-600">Not allowed to sell any nudes</li>
                <li className="text-gray-600">
                  If it voilates our privacy & DMCA complaints then image will
                  be removed
                </li>
              </ul>
            </div>

            {/* Author Card */}
            <div className="flex items-center space-x-6 rounded-lg bg-white p-6 shadow-lg">
              {/* Creator's Avatar */}
              <div className="shrink-0">
                <img
                  src="https://picsum.photos/id/237/200/300"
                  alt="Author Name"
                  className="border-accent-400 h-20 w-20 rounded-full border-2"
                />
              </div>

              {/* Creator's Details */}
              <div className="grow">
                <h3 className="text-accent-800 mb-2 text-2xl font-bold">X20</h3>
                <p className="mb-4 text-sm text-gray-600">
                  Born to create magic! Follow my journey!
                </p>
                <div className="flex space-x-4">
                  <span className="flex items-center space-x-2 text-gray-700">
                    <span className="font-medium text-black">100</span>
                    <span className="font-medium text-gray-600"> Artworks</span>
                  </span>
                  <span className="flex items-center space-x-2 text-gray-700">
                    <span className="font-medium text-black">2k</span>
                    <span className="font-medium text-gray-600">
                      {" "}
                      Followers
                    </span>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container mx-auto mt-12 rounded-lg bg-white p-6">
        <h2 className="mb-4 text-2xl font-bold">Comments</h2>

        <div className="flex items-start space-x-4  p-6 ">
          <img
            src="https://picsum.photos/id/237/200/300"
            alt="User Name"
            className="h-12 w-12 rounded-full"
          />

          <div className="flex-1">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold">{}</h3>
              <span className="text-sm text-gray-500">2 days ago</span>
            </div>
            <p className="mt-2 text-gray-600">
              This artwork is absolutely stunning! Great job.
            </p>
          </div>
        </div>
        {/* Add Comment Section */}
        <div className="mb-8 ">
          <h3 className="mb-4 text-lg font-semibold">Add a Comment:</h3>
          <textarea
            className="mb-4 w-full rounded-md border border-gray-300 p-3 focus:border-indigo-500 focus:outline-none"
            rows={4}
            placeholder="Share your thoughts..."
          />
          <button
            type="button"
            className="rounded-lg bg-gradient-to-r from-purple-400 to-pink-600 px-4 py-2 text-white transition duration-300 hover:from-purple-500 hover:to-pink-700"
          >
            Submit Comment
          </button>
        </div>

        {/* Comments List */}
        <div className="space-y-6">
          {/* Sample Comment */}
          {/* ... (rest of your comment cards) ... */}
        </div>
      </div>
    </section>
  );
};

export default ListingDetail;
